### ISSUE TITLE
Changing Max mines per cell mid game

### ISSUE THREAD

**Issue by XilefG** [LewisGaul/minegauler#119]
Starting a game with max mines per cell as 3 and then changing it to 1 makes you unable to flag multiple mines on a single cell

**Comment by XilefG** [comment]
Starting a game with max mines per cell as 3 and then changing it to 1 makes you unable to flag multiple mines on a single cell

**Comment by LewisGaul** [comment]
Fixed by 7d4c57eba9e06982c9c3f39566754917511ab569
