### ISSUE TITLE
Provide styles via 'themes'

### ISSUE THREAD

**Issue by LewisGaul** [LewisGaul/minegauler#156]

**Comment by Krish-bhardwaj** [comment]
Hi i am a fresher i would like to contribute to your open source project , i know basic of python and have worked with PYQT5 , urllib3,mysql-connector-python, with your help and guidance i can solve this issue . It woud be realy great if can you assign me this issue .

**Comment by LewisGaul** [comment]
Hi @Krish-bhardwaj, thanks for the interest in contributing! I'm afraid this issue is already being worked on by @JessToudic, are there any other issues that seem interesting to you? I'd be happy to help you get going!

**Comment by Krish-bhardwaj** [comment]
Ok no problem
