### ISSUE TITLE
Fix the window sizing

### ISSUE THREAD

**Issue by LewisGaul** [LewisGaul/minegauler#16]
For beginner the window is started up too big, and the window shouldn't be resizable in general.

**Comment by LewisGaul** [comment]
This comes down to solving the following:
- The `MinegaulerGUI` main window should:
  - Have a minimum size as dictated by the width required by the top panel (`PanelWidget`)
  - Have a fixed width equal to the width of the minefield widget (including the frame) or the minimum size, whichever is greater. (See `minegauler.frontend.main_window._BaseMainWindow._body_frame`).
  - Have a fixed height with no gaps between widgets.

In theory this should be easy...?

**Comment by XilefG** [comment]
Window should never have gaps when the board height is too small

**Comment by LewisGaul** [comment]
The visible issues are now fixed, although the approach should potentially be revisited at some point (e.g. when we want to allow scrolling around a big minefield).
