### ISSUE TITLE
unable to install requirements-dev.txt

### ISSUE THREAD

**Issue by deepgandhi** [LewisGaul/minegauler#178]
unable to resolve PyQt5 conflicts.

`Ignoring PyQt5: markers 'platform_system != "Windows"' don't match your environment
Collecting attrs==21.2.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting certifi==2021.5.30
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting charset-normalizer==2.0.4
  Using cached charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting idna==3.2
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting mysql-connector-python==8.0.26
  Using cached mysql_connector_python-8.0.26-cp39-cp39-win_amd64.whl (799 kB)
Collecting protobuf==3.17.3
  Using cached protobuf-3.17.3-cp39-cp39-win_amd64.whl (909 kB)
Collecting PyQt5==5.15.6
  Using cached PyQt5-5.15.6-cp36-abi3-win_amd64.whl (6.7 MB)
Collecting PyQt5-sip==12.9.0
  Using cached PyQt5_sip-12.9.0-cp39-cp39-win_amd64.whl (63 kB)
Collecting requests==2.26.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3==1.26.6
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting altgraph==0.17.2
  Using cached altgraph-0.17.2-py2.py3-none-any.whl (21 kB)
Collecting black==22.1.0
  Using cached black-22.1.0-cp39-cp39-win_amd64.whl (1.1 MB)
Collecting bleach==4.1.0
  Using cached bleach-4.1.0-py2.py3-none-any.whl (157 kB)
Collecting bump2version==1.0.1
  Using cached bump2version-1.0.1-py2.py3-none-any.whl (22 kB)
Collecting cffi==1.14.6
  Using cached cffi-1.14.6-cp39-cp39-win_amd64.whl (180 kB)
Collecting click==8.0.1
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting colorama==0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting coverage==5.5
  Using cached coverage-5.5-cp39-cp39-win_amd64.whl (211 kB)
Collecting cryptography==3.4.8
  Using cached cryptography-3.4.8-cp36-abi3-win_amd64.whl (1.6 MB)
Collecting docutils==0.17.1
  Using cached docutils-0.17.1-py2.py3-none-any.whl (575 kB)
Collecting Flask==2.0.1
  Using cached Flask-2.0.1-py3-none-any.whl (94 kB)
Collecting importlib-metadata==4.8.1
  Using cached importlib_metadata-4.8.1-py3-none-any.whl (17 kB)
Collecting iniconfig==1.1.1
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting isort==5.9.3
  Using cached isort-5.9.3-py3-none-any.whl (106 kB)
Collecting itsdangerous==2.0.1
  Using cached itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting jeepney==0.7.1
  Using cached jeepney-0.7.1-py3-none-any.whl (54 kB)
Collecting Jinja2==3.0.1
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting keyring==23.2.0
  Using cached keyring-23.2.0-py3-none-any.whl (33 kB)
Collecting MarkupSafe==2.0.1
  Using cached MarkupSafe-2.0.1-cp39-cp39-win_amd64.whl (14 kB)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting packaging==21.0
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Collecting pathspec==0.9.0
  Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting pkginfo==1.7.1
  Using cached pkginfo-1.7.1-py2.py3-none-any.whl (25 kB)
Collecting platformdirs==2.3.0
  Using cached platformdirs-2.3.0-py3-none-any.whl (13 kB)
Collecting pluggy==1.0.0
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting py==1.10.0
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting py-cpuinfo==8.0.0
  Using cached py-cpuinfo-8.0.0.tar.gz (99 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pycparser==2.20
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting Pygments==2.10.0
  Using cached Pygments-2.10.0-py3-none-any.whl (1.0 MB)
Collecting pyinstaller==4.9
  Using cached pyinstaller-4.9-py3-none-win_amd64.whl (2.0 MB)
Collecting pyinstaller-hooks-contrib==2022.0
  Using cached pyinstaller_hooks_contrib-2022.0-py2.py3-none-any.whl (222 kB)
Collecting pyparsing==2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
ERROR: Cannot install PyQt5==5.14.2 and PyQt5==5.15.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested PyQt5==5.15.6
    The user requested PyQt5==5.14.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by LewisGaul** [comment]
Thanks for reporting this, I've pushed a fix to the `dev` branch (see https://github.com/LewisGaul/minegauler/commit/9f10c21).
