### ISSUE TITLE
Remaining items for sorting out highscores

### ISSUE THREAD

**Issue by XilefG** [LewisGaul/minegauler#39]
- [x]  Handle drag select changing [mid-game]
- [ ]  Achieve reasonable test coverage (at least the new backend code)
- [ ]  Show settings corresponding to displayed highscores in highscore window
- [ ]  Update displayed highscores when a new one is set (call `get_highscores()` again - add a 'refresh' button?)
- [x]  Keep highscore window state when it is closed (e.g. the name filter)
- [x]  Do some manual performance/scale testing
- [ ]  Add compatibility layer for legacy DB files and convert to current DB structure
- [ ]  Handle opening highscores window when a custom difficulty is in play

_Originally posted by @LewisGaul in https://github.com/LewisGaul/minegauler/pull/37#issuecomment-569116281_

**Comment by LewisGaul** [comment]
Has been seen to perform very poorly with ~100 highscores shown at once.

**Comment by LewisGaul** [comment]
Closing in favour of #90.
